apiVersion: v1
kind: Service
metadata:
  name: ecsdemo-nodejs
spec:
  selector:
    app: ecsdemo-nodejs
  type: NodePort
  ports:
   -  protocol: TCP
      nodePort: 30816
      port: 80
      targetPort: 3000

